# Generated by Django 5.0.6 on 2024-09-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("floor", models.IntegerField(verbose_name="Этаж. 2 или 3")),
                ("start_hour", models.IntegerField(verbose_name="Начало в")),
                ("finish_hour", models.IntegerField(verbose_name="Конец в")),
                ("cost", models.IntegerField(verbose_name="Цена бронирования")),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
