# Generated by Django 5.0.6 on 2024-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="payment_type",
            field=models.CharField(
                default=None,
                max_length=15,
                null=True,
                verbose_name="Оплачено наличными или картой",
            ),
        ),
    ]
