# Generated by Django 5.0.6 on 2024-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "telegram_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Телеграм ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=20, verbose_name="username в Телеграм"),
                ),
                (
                    "registered_since",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(default=0, verbose_name="Бонусные баллы"),
                ),
            ],
        ),
    ]
